#!/bin/bash

sparforge=`dirname $0`
clojure_trunk=$HOME/devl/contrib/clojure-trunk/clojure.jar
clojure_contrib=$HOME/devl/contrib/clojure-contrib-trunk/clojure-contrib.jar

# Buid class path; any .jar under $sparforge/lib is placed on the classpath
classpath=".:$clojure_trunk:$clojure_contrib"
for jar in $sparforge/lib/*.jar
do
  classpath="${classpath}:$jar"
done

java -cp $classpath -Djava.library.path=$sparforge/lib clojure.main -i ui/main.clj -r
