#!/bin/bash

sparforge=`dirname $0`
clojure_trunk=$CLOJURE_HOME/clojure.jar
clojure_contrib=$CLOJURE_CONTRIB_HOME/clojure-contrib.jar
output=$sparforge/classes

mkdir -p $output

# Build class path; any .jar under $sparforge/lib is placed on the classpath
classpath=".:$clojure_trunk:$clojure_contrib:$output"
for jar in $sparforge/lib/*.jar
do
  classpath="${classpath}:$jar"
done

java -cp $classpath -Djava.library.path=$sparforge/lib clojure.main -i ui/main.clj -r
