#!/bin/bash

sparforge=`dirname $0`
clojure_trunk=/home/mike/devl/contrib/clojure-trunk/clojure.jar

# Buid class path; any .jar under $sparforge/lib is placed on the classpath
classpath="$clojure_trunk"
for jar in $home/lib/*.jar
do
  classpath="${cp}:$jar"
done

java -cp $classpath -Djava.library.path=$sparforge/lib clojure.main -i ui/main.clj -e "(ui.main/-main \"Sparforge\")" -r
